#-------------------------------
#GitHub Action Part-1 Basics
#by FVV
#-------------------------------
name: My-GitHubActions-Basics
env: 
  APPLICATION_NAME      : "My Flask"
  DEPLOY_PACKAGE_NAME   : "flask deploy-file-ver-${{ github.sha }}"
    
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
   My_testig:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Print Hello Message in testing
      run : echo "Hello World from Testing"
    
    - name: Execute few commands
      run: |
         echo "Hello Message1"
         echo "Hello Message2"
         echo "Application name: ${{ env.APPLICATION_NAME }}"
    
    - name: List current folder
      run: ls -la
  
    - name: Git clone my repo
      uses: actions/checkout@v1  
        
    - name: List current folder
      run: ls -la
   
   
   
   my_deploy:
     needs: [My_testig]
     runs-on: ubuntu-latest 
     env: 
        VAR1: "This is Job Level Variable1"
        VAR2: "This is Job Level Variable2"
     
     
     steps:
      - name: Print Hello Message in deploy
        run : echo "Hello World from Deploy job"  
     
      - name: Print env vars
        run: |
           echo "Var1 = ${{ env.VAR1 }}
           echo "Var2 = ${{ env.VAR2 }}
           echo "Var3 =$LOCAL_VAR"
        env:
          LOCAL_VAR: "This is super local Environment variable"
          
     
      
      - name: Printing Deployment package
        run: echo "Deploy packege name is ${{ env.DEPLOY_PACKAGE_NAME }}"
        
      - name: Lets test some packeges if they are here 1
        run: aws --version
      
      - name: Lets test some packeges if they are here 2
        run: zip --version
        
